import type { Metadata } from "next";
import UserDashboardHeader from "../user-dashboard-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserDashboard({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <UserDashboardHeader />
      {children}
    </section>
  );
}
