import type { Metadata } from "next";
import Link from "next/link";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserDashboard({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <ToastContainer
        position="top-right"
        hideProgressBar={true}
        autoClose={2000}
      />
      <ul>
        <li>
          <Link href="/users">User List</Link>
        </li>
        <li>
          <Link href="/users/registration">User Registration</Link>
        </li>
      </ul>
      {children}
    </section>
  );
}
